name: micropass_api
description: MicroPass API Client for Dart
version: 0.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5
  libcrypto: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker: ^2.0.0
